# Copyright (C) 2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

name: "Check and then upload packages (and potentially publish to PyPI)"
description: "Check the (already built) and upload packages as artifacts (and potentially publish onto Test and real PyPI servers)."
inputs:
  type:
    description: 'Type of packages.'
    required: true
  publish:
    description: 'Publish packages to PyPI.'
    default: false
  root_user:
    description: "Publish to PyPI from given user's repository."
    default:
  root_branch:
    description: 'Publish to PyPI on provided branch.'
    default: refs/heads/master

runs:
  using: "includes"

  steps:
  - name: ✔︎ Check wheels 📦
    if: inputs.type == 'wheels'
    shell: bash
    run: |
      PYVER=$(python2 -c "import sys; print(sys.version[0])")
      for WHEEL in dist/*.whl; do
        echo
        echo "::group::Checking $WHEEL"
        echo
        python -m zipfile -t $WHEEL
        python -m zipfile -l $WHEEL
        echo
        if [ "$(uname)" = "Linux" -a $PYVER -eq 3 ]; then
          auditwheel show $WHEEL
        fi
        echo
        twine check $WHEEL
        echo
        echo "::endgroup::"
      done

  - name: ✔︎ Check source 📦
    if: inputs.type == 'source'
    shell: bash
    run: |
      shopt -s nullglob
      for SRC in dist/*.zip; do
        echo
        echo "::group::Checking $SRC"
        echo
        python -m zipfile --test $SRC
        python -m zipfile --list $SRC
        echo
        twine check $SRC
        echo
        echo "::endgroup::"
      done
      for SRC in dist/*.t*gz; do
        echo
        echo "::group::Checking $SRC"
        echo
        python -m tarfile --list $SRC
        echo
        twine check $SRC
        echo
        echo "::endgroup::"
      done

  - name: 📤 Upload ${{ inputs.type }} 📦
    uses: actions/upload-artifact@v2
    with:
      name: ${{ inputs.type }}-${{ runner.os }}
      path: dist

  - name: 📤 Publish ${{ inputs.type }} to Test PyPI
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
    if: |
        inputs.publish &&
        (github.ref == inputs.root_branch) &&
        (env.TWINE_PASSWORD != null)
    run: |
      twine upload --skip-existing --verbose --repository testpypi dist/*

  - name: 📤 Publish $${{ inputs.type }} to PyPI
    if: |
        inputs.publish &&
        (github.ref == inputs.root_branch) &&
        startsWith(inputs.root_user, github.repository) &&
        (github.event_name != 'pull_request') &&
        (env.TWINE_PASSWORD != null)
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    run: |
      twine upload dist/*
