# Copyright (C) 2017-2022 F4PGA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Publish wheels for (binary) packages on PyPI.
description: ""
inputs:
  root_user:
    description: Repository name that should be publishing packages to PyPi.
    required: true
    default: SymbiFlow
  root_branch:
    description: Default branch to publish packages from.
    required: true
    default: refs/heads/master
  python-version:
    description: Python version to publish for.
    required: true
  build-requirements:
    description: Python (pip) packages required at build time, space-separated.
    default:
  system-packages:
    description: System (yum) packages required at build time, space-separated.
    default:
  pre-build-command:
    description: Command to run before build, e.g. the execution of a script to perform additional build-environment setup.
    default:
  package-path:
    description: Path to python package to build (e.g. where setup.py file is located), relative to repository root.
    default: ''
  pip-wheel-args:
    description: Extra extra arguments to pass to the pip wheel command (see pip documentation), passed paths are relative to package-path.
    default: -w ./dist --no-deps --verbose


runs:
  using: "includes"

  steps:

  # Linux -- manylinux
  # ----------------------------------------------------------------------
  - name: Config Check
    if: ${{ !startswith(runner.os, 'Linux') }}
    run: |
      echo "Use"
      echo
      echo "  SymbiFlow/actions/includes/actions/python/publish-to-pypi-sheels-bin-other"
      echo
      echo "for Windows / Mac"
      echo
      exit 1

  - name: Install packaging tooling on runner
    run: |
      echo "$HOME/.local/bin" >> $GITHUB_PATH
      export PATH=$HOME/.local/bin:$PATH
      pip install -U pip twine wheel auditwheel

  - name: Check packaging tooling on runner
    run: |
      echo $PATH
      which pip
      which twine
      which wheel
      which auditwheel

  - name: Workout manylinux-version
    id: manylinux
    shell: python
    env:
      PYTHON_VERSION: ${{ inputs.python-version }}
    run: |
      import os
      MANYLINUX = {
          "3.6": "cp36-cp36m",
          "3.7": "cp37-cp37m",
          "3.8": "cp38-cp38",
          "3.9": "cp39-cp39",
      }[os.environ['PYTHON_VERSION']]
      print("::set-output name=version::"+MANYLINUX)

  - name: 🚧 Build distribution 📦
    uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2010_x86_64
    with:
      build-requirements: ${{ inputs.build-requirements }}
      system-packages: ${{ inputs.system-packages }}
      python-versions: ${{ steps.manylinux.outputs.version }}
      pre-build-command: ${{ inputs.pre-build-command }}
      package-path: ${{ inputs.package-path }}
      pip-wheel-args: ${{ inputs.pip-wheel-args }}

  - name: List distribution 📦
    run: |
      # Fix permissions
      echo "::group::Fixing permission"
      ls -l dist/*
      echo $USER
      whoami
      sudo chown -R $USER dist
      ls -l dist/*
      echo "::endgroup::"
      # Remove the non-manylinux versions
      rm -v dist/*linux_x86_64*.whl
      ls -l dist/*
  # ----------------------------------------------------------------------

  # Upload the packages
  # ----------------------------------------------------------------------
  - includes: ./includes/actions/python/check-upload-publish-packages
    with:
      type: wheels
      publish: true
      root_user: ${{ inputs.root_user }}
      root_branch: ${{ inputs.root_branch }}
  # ----------------------------------------------------------------------
