# Copyright (C) 2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:	ISC

name: 'Conda Lock Updating Action'
description: 'Updates the conda lock file'

inputs:
  environment_file:
    description: 'Path of the `environment.yml` file'
  conda_lock_file:
    description: 'Path of the Conda Lock file (needs to have txt/yml/yaml extension)'

runs:
  using: "composite"
  steps:
  - shell: bash
    run:   $GITHUB_ACTION_PATH/check_prepare_env.sh

  - shell: bash
    run: |
      set -e
      source $GITHUB_ACTION_PATH/helpers.sh

      function set_env {
        echo "$1=${2:-$3}" >> $GITHUB_ENV
      }
      set_env BOT_CONDA_LOCK   "${{ inputs.conda_lock_file }}"    "conda_lock.yml"
      set_env BOT_ENV_YML      "${{ inputs.environment_file }}"   "environment.yml"
      gend

  # Uses BOT_CONDA_LOCK and BOT_ENV_YML
  - shell: bash
    run:   $GITHUB_ACTION_PATH/update_lock.sh
