# Copyright (C) 2021-2022 F4PGA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: 'Conda Lock Updating Action'
description: 'Updates the conda lock file'

inputs:
  environment_file:
    description: 'Path of the `environment.yml` file'
  conda_lock_file:
    description: 'Path of the Conda Lock file (needs to have txt/yml/yaml extension)'

runs:
  using: "composite"
  steps:
  - shell: bash
    run:   $GITHUB_ACTION_PATH/check_prepare_env.sh

  - shell: bash
    run: |
      set -e
      source $GITHUB_ACTION_PATH/helpers.sh

      function set_env {
        echo "$1=${2:-$3}" >> $GITHUB_ENV
      }
      set_env BOT_CONDA_LOCK   "${{ inputs.conda_lock_file }}"    "conda_lock.yml"
      set_env BOT_ENV_YML      "${{ inputs.environment_file }}"   "environment.yml"
      gend

  # Uses BOT_CONDA_LOCK and BOT_ENV_YML
  - shell: bash
    run:   $GITHUB_ACTION_PATH/update_lock.sh
