name: 'Checks'
description: "Run license and linting checks"

inputs:

  debug:
    description: Output extra debug information
    default: false

  thirdPartyExclude:
    description: 'List of directory patterns to consider third_party resources.'
    default: >
      third_party

  directoryExclude:
    description: 'List of dir/file patterns to exclude from all checks'
    default: >
      .git
      *env
      build
      *cache*

  licenseExclude:
    description: 'List of dir/file patterns to exclude from the license checks'
    default: >
      */*/__init__.py
      ./miniconda.sh

  pythonExclude:
    description: 'List of dir/file patterns to exclude from the Python checks'
    default: >
      */.*
      */__pycache__/*
      */.pytest_*/*


runs:
  using: 'docker'
  image: 'Dockerfile'
